---
sudo: required
dist: xenial
language: python
python:
  - "3.7"
services:
  - docker
env:
  global:
    - PATH="/usr/bin:$PATH"

# Ansible doesn't play well with virtualenv
before_install:
  - deactivate
  - sudo apt-get update -qq
  - sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-ce

install:
  - pip install yamllint docker molecule molecule[lint] molecule[docker]
  # software-properties-common for ubuntu 14.04
  # python-software-properties for ubuntu 12.04
  - sudo apt-get install -y sshpass software-properties-common python-software-properties
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update -qq
  - sudo apt-get install -y ansible
  - sudo rm /usr/bin/python && sudo ln -s /usr/bin/python3.7 /usr/bin/python
script:
  - ansible-playbook -i tests/inventory.ini tests/test.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  - molecule test

notifications:
  # notify ansible galaxy of test results
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
