---
language: python
python: "3.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
      - python-pip
      - libssl-dev

install:
  - virtualenv .env
  - .env/bin/pip install -U pip
  - .env/bin/pip install ansible molecule molecule[lint]

  # Check ansible version
  - .env/bin/ansible --version

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - cp -r java_role lordoftheflies.java_role
  - cd lordoftheflies.java_role
script:
  # Basic role syntax check
  - .env/bin/ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - .env/bin/molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
