---
language: python
python: "3.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
      - python3-pip
      - libssl-dev

install:
  - pip install -U pip
  - pip install ansible docker molecule[docker] molecule molecule[lint] yamllint

  # Check ansible version
  - ansible --version

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - cp -r ssl_role lordoftheflies.ssl_role
  - cd lordoftheflies.ssl_role
script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory.ini --syntax-check
  - molecule test -s docker

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
