---
- name: "Set fact certificate-authority fqdn"
  set_fact:
    certificate_authority_hostname: certificate_authority
  tags: ["ssl", "ca"]
- debug: var=certificate_authority_hostname, verbosity=1

- name: "Create host group from all public endpoint-host which public and secure"
  tags: ["ssl"]
  add_host:
    name: "{{ endpoint }}"
    groups: ssl_servers
    certificate_authority: "{{ certificate_authority }}"
  with_items:
    - "{{ groups['all'] }}"
  loop_control:
    loop_var: endpoint
  when: >
    (public is defined and public | length > 0)
    and
    (secure is defined and secure | length > 0)
    and
    (endpoint is defined and secure | length > 0)

- name: "Show hosts need a certificate"
  tags: ["ssl"]
  debug: msg="{{ item }}", verbosity=1
  with_items:
    - "{{ groups['ssl_servers'] }}"

- name: "Set fact of SSL certificate fqdn list"
  set_fact:
    client_certificates: "{{ existing_certificates + groups['ssl_servers'] }}"
- debug: var=client_certificates, verbosity=1

- name: "Play SSL for each CA"
  when: "'ssl_servers' not in group_names"
  block:
    - debug: msg="endpoint={{ inventory_hostname }} "
    - import_tasks: ssl.yml
  rescue:
    - debug: msg="Securing {{ inventory_hostname }} failed"
  always:
    - debug: msg="Certificates issued"