---

- name: "Create index file"
  tags: ['ssl', 'ca', 'openssl', 'configure']
  become: true
  become_user: root
  file:
    path: /root/ca/index.txt
    state: "{{ 'touch' if state|default('present') == 'present' else 'absent' }}"

- name: "Create file where OpenSSL keeps track of all signed certificates"
  tags: ['ssl', 'ca', 'openssl', 'configure']
  become: true
  file:
    src: serial
    dest: /root/ca/serial
    state: state | default('present')
