---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: true
  no_log: "{{ molecule_no_log }}"
  tasks:

    - name: "Initialize"
      set_fact:
        server: {}
    - name: "Initialize"
      set_fact:
        server:
          results: []

    - name: "Create instances"
      set_fact:
        server:
          results: "{{ ([ {
            'name': item.name,
            'instance': item.instance,
            'ipv4': item.ipv4,
            'username': item.user,
            'password': item.password,
            'hardware': {
              'memory_mb': item.memory | default(omit),
              'num_cpus': item.cpu | default(omit),
            },
            'wait_for_ip_address': true,
            'state': 'poweredon',
            'timestamp': ansible_date_time.iso8601,
          } ] + server.results) }}"
          changed: true
      with_items: "{{ molecule_yml.platforms }}"
    - debug: var=server.results, verbosity=0

    - name: "Externalize"
      copy:
        content: "{{ item | to_json }}"
        dest: "{{ item.name }}.env.json"
      delegate_to: localhost
      with_items: "{{ server.results }}"
    # Developer must map instance config.
    # Mandatory configuration for Molecule to function.

    - name: "Populate instance config dict"
      set_fact:
        instance_conf_dict: {
          'name': "{{ item.name }}",
          'instance': "{{ item.instance }}",
          'address': "{{ item.ipv4 }}",
          'user': "{{ item.username }}",
          'port': "22",
          'identity_file': "~/.ssh/id_rsa",
        }
      with_items: "{{ server.results }}"
      register: instance_config_dict
      when: server.changed | bool

    - name: Convert instance config dict to a list
      set_fact:
        instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"
      when: server.changed | bool

    - name: Dump instance config
      copy:
        content: "{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"
        dest: "{{ molecule_instance_config }}"
      when: server.changed | bool
