---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: true
  no_log: "{{ molecule_no_log }}"
  tasks:
    # Developer must implement.
    - name: "Initialize"
      set_fact:
        server: {}
    - name: "Initialize"
      set_fact:
        server:
          results: []
    # Mandatory configuration for Molecule to function.
    - name: Load instance config
      set_fact:
        server:
          results: "{{ server.results + [ lookup('file', item.name + '.env.json') | from_json ] }}"
          changed: true
      delegate_to: localhost
      with_items: "{{ molecule_yml.platforms }}"

    - name: Populate instance config
      set_fact:
        instance_conf: {
          'instance': "{{ item.instance }}",
          'address': "{{ item.ipv4 }}",
          'user': "{{ item.username }}",
          'port': 22,
          'identity_file': "~/.ssh/id_rsa",
          'timestamp': "{{ item.timestamp }}"
        }
      with_items: "{{ server.results }}"
    - debug: var=instance_conf

    - name: Dump instance config
      copy:
        content: "{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"
        dest: molecule_instance_config
      when: server.changed | bool
