# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

USER root

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y python3.7 sudo bash ca-certificates iproute2 && apt-get clean; \
    elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install python3.7 sudo python-devel python*-dnf bash iproute && dnf clean all; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum install -y python3.7 sudo yum-plugin-ovl bash iproute && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    elif [ $(command -v zypper) ]; then zypper refresh && zypper install -y python3.7 sudo bash python-xml iproute2 && zypper clean -a; \
    elif [ $(command -v apk) ]; then apk update && apk add --no-cache python3.7 sudo bash ca-certificates; \
    elif [ $(command -v xbps-install) ]; then xbps-install -Syu && xbps-install -y python3.7 sudo bash ca-certificates iproute2 && xbps-remove -O; fi

RUN set -x && apt-get install -y openssh-server openssh-client

RUN mkdir /var/run/sshd
#RUN echo '$ANSIBLE_USER:qwe123' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/#Port 22/Port 22/' /etc/ssh/sshd_config
RUN sed -i 's/#ListenAddress 0.0.0.0/ListenAddress 0.0.0.0/' /etc/ssh/sshd_config
RUN sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/' /etc/ssh/sshd_config
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
RUN chmod 755 -R /var/run/sshd

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

RUN adduser $ANSIBLE_USER

RUN mkdir -p /home/$ANSIBLE_USER/.ssh
# ADD id_rsa /home/$ANSIBLE_USER/.ssh/id_rsa
#RUN chmod 600 /home/$ANSIBLE_USER/.ssh/id_rsa
#ADD id_rsa.pub /home/$ANSIBLE_USER/.ssh/id_rsa.pub
#RUN chmod 600 /home/$ANSIBLE_USER/.ssh/id_rsa.pub
RUN echo ${PUBLIC_SSH_KEY} >> /home/$ANSIBLE_USER/.ssh/authorized_keys
RUN chmod -R go= /home/$ANSIBLE_USER/.ssh

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22/tcp
WORKDIR /home/$ANSIBLE_USER
CMD ["/usr/sbin/sshd", "-D"]
