---
dependency:
  name: galaxy
driver:
  name: delegated
lint:
  name: yamllint
  options:
    config-file: .ansible-lint
platforms:
  - name: stage
    address: ssh_endpoint
    identity_file: ssh_identity_file  # mutually exclusive with password
    instance:
      hw_name: leviathan.cherubits.hu
      ipv4: 127.0.0.1
    port: ssh_port_as_string
    user: ssh_user
    password: ssh_password  # mutually exclusive with identity_file
    become_method: valid_ansible_become_method  # optional
    become_pass: password_if_required  # optional
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
  inventory:
    hosts:
      all:
      ssl_servers:
        hosts:
          'a.ssl.test':
          'b.ssl.test':
          'c.ssl.test':
        vars:
          endpoint: true
          public: true
          secure: true
verifier:
  name: testinfra
  lint:
    name: flake8
