---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .ansible-lint
platforms:
  - name: ubuntu1804
    hostname: 'a.ssl.test'
    image: "registry.hub.docker.com/ubuntu:18.04"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    dockerfile: Dockerfile.j2
    pull: true
    registry:
      url: registry.hub.docker.com
      credentials:
        username: lordoftheflies
        password: 90e22074-32e9-4485-a292-4deee07227c6
        email: laszlo.hegedus@cherubits.hu
        user: root
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
  inventory:
    hosts:
      all:
      ssl_servers:
        hosts:
          'a.ssl.test':
            endpoint: 'a.ssl.test'
            public: 'a.ssl.test'
            secure: 'a.ssl.test'
verifier:
  name: testinfra
  lint:
    name: flake8
